# stack

In [ ]:
import torch

# 假设是时间步T1的输出
T1 = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
# 假设是时间步T2的输出
T2 = torch.tensor([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
T1:tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
T2:tensor([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
测试stack函数

R0 = torch.stack((T1, T2), dim=0)
print("R0:\n", R0)
print("R0.shape:\n", R0.shape)
"""
R0:tensor([[[ 1,  2,  3],[ 4,  5,  6],[ 7,  8,  9]],[[10, 20, 30],[40, 50, 60],[70, 80, 90]]])
R0.shape:torch.Size([2, 3, 3])
"""R1 = torch.stack((T1, T2), dim=1)
print("R1:\n", R1)
print("R1.shape:\n", R1.shape)
"""
R1:tensor([[[ 1,  2,  3],[10, 20, 30]],[[ 4,  5,  6],[40, 50, 60]],[[ 7,  8,  9],[70, 80, 90]]])
R1.shape:torch.Size([3, 2, 3])"""R2 = torch.stack((T1, T2), dim=2)
print("R2:\n", R2)
print("R2.shape:\n", R2.shape)
"""
R2:tensor([[[ 1, 10],[ 2, 20],[ 3, 30]],[[ 4, 40],[ 5, 50],[ 6, 60]],[[ 7, 70],[ 8, 80],[ 9, 90]]])
R2.shape:torch.Size([3, 3, 2])"""R3 = torch.stack((T1, T2), dim=3)
print("R3:\n", R3)
print("R3.shape:\n", R3.shape)
"""
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [2]:
import torch

# 假设是时间步T1的输出
T1 = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
torch.stack([T1], dim=1)

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [3]:
torch.stack([T1], dim=1).size()

torch.Size([3, 1, 3])

In [18]:
T1 = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # 1*1*3
print('T1 size:', T1.size())

print(torch.stack([T1], dim=-1).size())
print(torch.stack([T1], dim=-1))

T1 size: torch.Size([3, 3])
torch.Size([3, 3, 1])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


In [17]:
T1 = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]]) # 1*1*3
print('T1 size:', T1.size())

print(torch.stack([T1, T1], dim=-1).size())
print(torch.stack([T1, T1], dim=-1))

t_stack = torch.stack([T1, T1], dim=-1)
print(t_stack.reshape(t_stack.shape[0], t_stack.shape[1], -1).size())
print(t_stack.reshape(t_stack.shape[0], t_stack.shape[1], -1))

T1 size: torch.Size([1, 3, 3])
torch.Size([1, 3, 3, 2])
tensor([[[[1, 1],
          [2, 2],
          [3, 3]],

         [[4, 4],
          [5, 5],
          [6, 6]],

         [[7, 7],
          [8, 8],
          [9, 9]]]])
torch.Size([1, 3, 6])
tensor([[[1, 1, 2, 2, 3, 3],
         [4, 4, 5, 5, 6, 6],
         [7, 7, 8, 8, 9, 9]]])


In [9]:
print(torch.stack([T1, T1], dim=1).size())
print(torch.stack([T1, T1], dim=1))

torch.Size([3, 2, 3])
tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]],

        [[7, 8, 9],
         [7, 8, 9]]])


# expand, tolist

In [19]:
import torch

x = torch.tensor([[1], [2], [3]])
x.size()
type(x[0][0].item())

print(x.tolist(), type(x.tolist()))

[[1], [2], [3]] <class 'list'>


In [14]:
x.expand(-1, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

# to numpy

In [3]:
import torch

x = torch.tensor([[1], [2], [3]])

x.numpy()

array([[1],
       [2],
       [3]], dtype=int64)

# cat

* All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [12]:
x = torch.rand([2,2, 3])

print(x)

m = torch.tensor([
    [[1], [0]],
    [[2], [0]]
])

print(m.shape)

print(x * m)

tensor([[[0.4448, 0.1296, 0.2365],
         [0.7991, 0.6418, 0.6442]],

        [[0.5764, 0.7893, 0.3151],
         [0.6487, 0.9094, 0.8953]]])
torch.Size([2, 2, 1])
tensor([[[0.4448, 0.1296, 0.2365],
         [0.0000, 0.0000, 0.0000]],

        [[1.1528, 1.5786, 0.6301],
         [0.0000, 0.0000, 0.0000]]])


# torch.split() and torch.chunk(). torch.clamp


# normal distribution and log_prob

In [20]:
from torch.distributions import Normal

mu = torch.tensor([1, 10], dtype=torch.float32)
sigma = torch.tensor([1], dtype=torch.float32)
 
dist = Normal(mu, sigma)  # 设置高斯分布的均值和方差
 
dist.sample()  # 采样

tensor([1.1439, 9.8823])

In [21]:
x = torch.tensor([1, 10, 10, 1], dtype=torch.float32).reshape(-1, 2)

dist.log_prob(x)

tensor([[ -0.9189,  -0.9189],
        [-41.4189, -41.4189]])

In [22]:
dist.log

tensor([[ 1., 10.],
        [10.,  1.]])