# Basis

## add a column

In [1]:
import numpy as np
N = 10
a = np.random.rand(N, N)
b = np.zeros((N, N+1))
b[:, :-1] = a


In [2]:
%timeit b = np.hstack((a,np.zeros((a.shape[0],1))))

%timeit b = np.zeros((a.shape[0],a.shape[1]+1)); b[:,:-1] = a


4.17 µs ± 30.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.06 µs ± 3.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
b = np.hstack((a, np.zeros((a.shape[0], 1))))
b

array([[0.02916295, 0.87899708, 0.81395871, 0.21538511, 0.64197281,
        0.58383717, 0.06290201, 0.43130597, 0.07383595, 0.70287672,
        0.        ],
       [0.83659737, 0.68391684, 0.23613578, 0.77461555, 0.20492765,
        0.75582207, 0.17991717, 0.74398712, 0.43116549, 0.57545911,
        0.        ],
       [0.44465171, 0.09492569, 0.04310519, 0.81412942, 0.52546005,
        0.47538229, 0.29373988, 0.80104508, 0.27112389, 0.31419257,
        0.        ],
       [0.37581401, 0.70629913, 0.96582592, 0.927091  , 0.55186695,
        0.63423822, 0.7913479 , 0.5905351 , 0.99477437, 0.48128527,
        0.        ],
       [0.48356148, 0.38283685, 0.43211902, 0.62945134, 0.13363901,
        0.69609255, 0.19410702, 0.07033801, 0.38839862, 0.37334202,
        0.        ],
       [0.41534671, 0.89919983, 0.05261041, 0.32655715, 0.88714088,
        0.52143346, 0.2305311 , 0.31443906, 0.13001226, 0.11326674,
        0.        ],
       [0.03376557, 0.36063834, 0.70846747, 0.87698505, 0.

## add a row

In [3]:
from numpy import array

A = array([[0, 1, 2], [0, 2, 0]])
X = array([[0, 1, 2], [1, 2, 0], [2, 1, 2], [3, 2, 0]])

A = np.vstack((A, X[X[:,0] < 3]))
A

array([[0, 1, 2],
       [0, 2, 0],
       [0, 1, 2],
       [1, 2, 0],
       [2, 1, 2]])

## expand dims

In [5]:
import numpy as np

a = np.ones(shape=[3, 4])

print(a, "\n", np.expand_dims(a, axis=-1).shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 (3, 4, 1)


# concatenate

In [2]:
a = np.array([1, 2])
b = np.array([5, 6])
np.concatenate((a, b), axis=0)
np.vstack([a, b])

array([[1, 2],
       [5, 6]])

In [5]:
c = np.array([])
np.append(c, a)

array([1., 2.])

# linearspace

In [1]:
import numpy as np
np.linspace(1, 10, num=3)

array([ 1. ,  5.5, 10. ])